### ISSUE TITLE
1.12 Crash while loading world

### ISSUE THREAD

**Issue by purestone9** [gottsch/gottsch-minecraft-FastLadder#1]
Playing with the Skyblock Godless modpack.
[crash-2017-07-19_13.36.13-Client.txt](https://github.com/gottsch/gottsch-minecraft-FastLadder/files/1160274/crash-2017-07-19_13.36.13-Client.txt)
[crash-2017-07-19_13.37.56-Client.txt](https://github.com/gottsch/gottsch-minecraft-FastLadder/files/1160275/crash-2017-07-19_13.37.56-Client.txt)

**Comment by gottsch** [comment]
Thanks purestone9 for posting the issue here.

This actually has multiple issues.
1. the modEnable config properly wasn't being set on initialization in GottschCore.
2. FastLadder implemented it's own copy of latestVersion property and getters/setters and wasn't accessible in the AbstractMod since it had it's own property.
